from __future__ import annotations
import argparse,json,tempfile,zipfile
from pathlib import Path
SCENARIOS={"VFIB-STEMI-001","TORSADES-LQT-002","VT-ISCHEMIC-003","AFIB-RVR-SEPSIS-004","CHB-HYPERK-005","BRADY-DIGTOX-006","SVT-PSVT-007","NSVT-ECTOPY-008"}
FIELDS={"episodeSummary","mostLikelyEtiologyAndClinicalContext","contributingFactors","materialEtiologicUncertainty"}

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('zip_path'); a=ap.parse_args(); p=Path(a.zip_path).resolve(); errors=[]
 with tempfile.TemporaryDirectory() as td:
  with zipfile.ZipFile(p) as z:z.extractall(td)
  root=Path(td); m=json.loads((root/'manifest.json').read_text(encoding='utf-8'))
  for key,val in {"schemaVersion":"kgen-colab-medical-batch-v3","promptVersion":"episode-pack-phase6-v6.0.3","responseContractVersion":"model-clinical-output-v6.0.3","contextMode":"episode_pack_only","itemCount":8}.items():
   if m.get(key)!=val: errors.append(f"manifest {key}: {m.get(key)!r} != {val!r}")
  found={i.get('scenarioId') for i in m.get('items',[])}
  if found!=SCENARIOS: errors.append(f"scenario set mismatch: {sorted(found)}")
  fps=[]
  for scenario in SCENARIOS:
   d=root/'items'/scenario
   for name in ('messages.json','model_clinical_evidence.json','diagnostic_event.json','validator_evidence.json','metadata.json'):
    if not (d/name).is_file(): errors.append(f"{scenario}: missing {name}")
   if (d/'messages.json').is_file():
    messages=json.loads((d/'messages.json').read_text(encoding='utf-8')); text=json.dumps(messages).lower()
    for term in ('incart','api range','oracle','fhir','generated by the slm','not an independent diagnosis','available=no','value=null'):
     if term in text: errors.append(f"{scenario}: forbidden prompt term {term}")
   if (d/'metadata.json').is_file(): fps.append(json.loads((d/'metadata.json').read_text()).get('promptFingerprint'))
  if len(set(fps))!=8: errors.append('prompt fingerprints are not unique')
 report={"valid":not errors,"itemCount":len(found),"errors":errors}; print(json.dumps(report,indent=2))
 if errors: raise SystemExit(1)
if __name__=='__main__':main()
