from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

from app.evaluation_injection.grounded_prompt_builder import build_grounded_messages
from app.evaluation_injection.model_clinical_evidence import (
    build_model_clinical_evidence,
    presentation_narrative_from_legacy,
)


SCENARIOS = (
    "VFIB-STEMI-001",
    "TORSADES-LQT-002",
    "VT-ISCHEMIC-003",
    "AFIB-RVR-SEPSIS-004",
    "CHB-HYPERK-005",
    "BRADY-DIGTOX-006",
    "SVT-PSVT-007",
    "NSVT-ECTOPY-008",
)

FORBIDDEN_PROMPT_TERMS = (
    "INCART",
    "API Range",
    "Oracle",
    "FHIR",
    "SMART",
    "reference annotation",
    "independent diagnosis",
    "raw ECG arrays",
    "waveform storage",
    "deduplicated",
    "source manifest",
    "evaluation detector",
    "model ownership",
    "generated by the SLM",
    "available=no",
    "value=null",
    "measured_unspecified_pattern",
)


def read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def find_episode(dataset_root: Path, scenario_id: str) -> Path:
    candidates = (
        dataset_root / "episodes" / f"{scenario_id}.json",
        dataset_root / f"{scenario_id}.json",
    )
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"Episode pack not found for {scenario_id}. Checked: "
        + ", ".join(str(path) for path in candidates)
    )


def diagnosis_display(pack: dict[str, Any], scenario_id: str) -> str:
    episode = pack.get("episode") or {}
    ecg = pack.get("ecg") or {}
    measurements = ecg.get("measurements") or {}
    return str(
        episode.get("display")
        or measurements.get("rhythm")
        or episode.get("type")
        or scenario_id
    )


def build_envelope(pack: dict[str, Any], scenario_id: str) -> dict[str, Any]:
    return {
        "schemaVersion": "slm-evidence-envelope-v4",
        "clinicalPromptMode": "episode_pack_only",
        "controlledRhythm": {
            "diagnosis": {
                "display": diagnosis_display(pack, scenario_id),
                "code": str((pack.get("episode") or {}).get("type") or scenario_id),
                "authoritative": True,
            }
        },
        "episodePackContext": pack,
        "deterministicAnalysis": {},
        "measurementConflicts": [],
    }


def find_run_dir(evaluated_root: Path | None, scenario_id: str) -> Path | None:
    if evaluated_root is None or not evaluated_root.exists():
        return None
    direct = evaluated_root / scenario_id / "run-1"
    if direct.exists():
        return direct
    matches = list(evaluated_root.rglob(f"{scenario_id}/run-1"))
    return matches[0] if len(matches) == 1 else None


def baseline_metrics(run_dir: Path | None) -> tuple[str | None, int | float | None, str]:
    if run_dir is None:
        return None, None, "not_available"
    validation = read_json(run_dir / "grounding_validation_v4.json")
    score = read_json(run_dir / "evaluation_score.json")
    status = validation.get("groundingStatus") or validation.get("status")
    return status, score.get("total"), "baseline_pre_v6_0_2_artifact"


def generated_output_status(run_dir: Path | None) -> tuple[bool | None, str, str]:
    if run_dir is None:
        return None, "not_rerun", "not_rerun"
    record = read_json(run_dir / "cardinal_model_response.attempt-1.json")
    raw = record.get("rawModelResponse") or {}
    if not isinstance(raw, dict):
        return None, "not_rerun", "not_rerun"
    four = {
        "episodeSummary",
        "mostLikelyEtiologyAndClinicalContext",
        "contributingFactors",
        "materialEtiologicUncertainty",
    }
    if four.issubset(raw):
        narrative = presentation_narrative_from_legacy(raw)
        uncertainty = narrative.get("materialEtiologicUncertainty") or []
        return True, "empty" if not uncertainty else "material_or_review_needed", "v6_0_2_four_field_output"
    return False, "legacy_output", "baseline_pre_v6_0_2_artifact"


def verify_one(
    *,
    dataset_root: Path,
    scenario_id: str,
    evaluated_root: Path | None,
) -> dict[str, Any]:
    pack = read_json(find_episode(dataset_root, scenario_id))
    envelope = build_envelope(pack, scenario_id)
    compact = build_model_clinical_evidence(evidence_bundle=envelope)
    messages = build_grounded_messages(evidence_bundle=envelope)
    prompt = "\n".join(str(item.get("content") or "") for item in messages)
    prompt_lower = prompt.lower()
    compact_text = json.dumps(compact, ensure_ascii=False).lower()

    forbidden_hits = [
        term
        for term in FORBIDDEN_PROMPT_TERMS
        if term.lower() in prompt_lower
    ]
    missing_hits = [
        marker
        for marker in (
            "available=no",
            "available=false",
            "value=null",
            "measured_unspecified_pattern",
            '"value": null',
        )
        if marker in compact_text or marker in prompt_lower
    ]

    run_dir = find_run_dir(evaluated_root, scenario_id)
    validator_status, score, baseline_source = baseline_metrics(run_dir)
    four_fields, uncertainty_status, output_source = generated_output_status(run_dir)

    return {
        "scenarioId": scenario_id,
        "forbiddenPromptTermsAbsent": not forbidden_hits,
        "forbiddenPromptHits": forbidden_hits,
        "missingPlaceholdersAbsent": not missing_hits,
        "missingPlaceholderHits": missing_hits,
        "compactTopLevelSections": list(compact.keys()),
        "fourRequiredContentBlocksProduced": four_fields,
        "uncertaintyStatus": uncertainty_status,
        "modelOutputSource": output_source,
        "validatorStatus": validator_status,
        "benchmarkScore": score,
        "validatorAndScoreSource": baseline_source,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset-root", default="SLM_Eval")
    parser.add_argument("--evaluated-root", default=None)
    parser.add_argument("--output-json", default="verification_table_v6_0_2.json")
    parser.add_argument("--output-csv", default="verification_table_v6_0_2.csv")
    args = parser.parse_args()

    dataset_root = Path(args.dataset_root).expanduser().resolve()
    evaluated_root = (
        Path(args.evaluated_root).expanduser().resolve()
        if args.evaluated_root
        else None
    )

    rows = [
        verify_one(
            dataset_root=dataset_root,
            scenario_id=scenario_id,
            evaluated_root=evaluated_root,
        )
        for scenario_id in SCENARIOS
    ]

    output = {
        "schemaVersion": "compact-prompt-verification-v6.0.2",
        "datasetRoot": str(dataset_root),
        "evaluatedRoot": str(evaluated_root) if evaluated_root else None,
        "allPromptChecksPassed": all(
            row["forbiddenPromptTermsAbsent"]
            and row["missingPlaceholdersAbsent"]
            for row in rows
        ),
        "rows": rows,
    }
    Path(args.output_json).write_text(
        json.dumps(output, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    fieldnames = [
        "scenarioId",
        "forbiddenPromptTermsAbsent",
        "missingPlaceholdersAbsent",
        "fourRequiredContentBlocksProduced",
        "uncertaintyStatus",
        "validatorStatus",
        "benchmarkScore",
        "modelOutputSource",
        "validatorAndScoreSource",
    ]
    with Path(args.output_csv).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key) for key in fieldnames})

    print(json.dumps(output, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
