from __future__ import annotations

ALGORITHM_VERSION = "phase-6-v1.1.1"
EPISODE_SCHEMA_VERSION = "episode-analysis-v1"
INCIDENT_SCHEMA_VERSION = "incident-analysis-v1"

EXPECTED_ECG_LEADS = (
    "lead1",
    "lead2",
    "lead3",
    "avr",
    "avl",
    "avf",
    "v1",
    "v2",
    "v3",
    "v4",
    "v5",
    "v6",
)

# Engineering defaults for ECG measured in millivolts.
# These are deterministic measurement thresholds, not diagnostic criteria.
MIN_SAMPLING_RATE_HZ = 100.0
MAX_SAMPLING_RATE_HZ = 2000.0
MIN_SIGNAL_SECONDS = 1.0

MAX_INVALID_PERCENT_USABLE = 2.0
MAX_INVALID_PERCENT_ANALYZABLE = 20.0

FLATLINE_DELTA_MV = 0.003
FLATLINE_MIN_SECONDS = 0.40
FLATLINE_MAX_PERCENT_USABLE = 10.0

REPEATED_EXTREMA_TOLERANCE_MV = 0.002
REPEATED_EXTREMA_RUN_SAMPLES = 4
CLIPPING_EXTREMA_PERCENTILE = 99.8
CLIPPING_MAX_PERCENT_USABLE = 2.0

DISCONTINUITY_ROBUST_Z = 12.0
DISCONTINUITY_MIN_MV = 1.5
MAX_DISCONTINUITIES_PER_MINUTE = 12.0

LOW_AMPLITUDE_ROBUST_RANGE_MV = 0.08
HIGH_AMPLITUDE_ROBUST_RANGE_MV = 12.0
MAX_DC_OFFSET_MV = 2.5
MAX_BASELINE_WANDER_RMS_MV = 0.35
MAX_HF_NOISE_RMS_MV = 0.18

BASELINE_CUTOFF_HZ = 0.50
BANDPASS_LOW_HZ = 0.50
BANDPASS_HIGH_HZ = 40.0
FILTER_ORDER = 4

NOTCH_FREQUENCY_HZ = 60.0
NOTCH_QUALITY_FACTOR = 30.0
NOTCH_ENABLE_MIN_SPECTRAL_RATIO = 8.0

RPEAK_MIN_DISTANCE_SECONDS = 0.25
RPEAK_PROMINENCE_MULTIPLIER = 3.0
RPEAK_MIN_PROMINENCE_MV = 0.08
RPEAK_CONSENSUS_TOLERANCE_SECONDS = 0.06
RPEAK_MIN_CONSENSUS_LEADS = 2

TRIGGER_ALIGNMENT_GOOD_MS = 80.0
TRIGGER_ALIGNMENT_ACCEPTABLE_MS = 150.0

BEAT_PRE_R_SECONDS = 0.30
BEAT_POST_R_SECONDS = 0.50

QRS_SEARCH_PRE_SECONDS = 0.12
QRS_SEARCH_POST_SECONDS = 0.16
QRS_EDGE_FRACTION = 0.12
QRS_MIN_DURATION_MS = 35.0
QRS_MAX_DURATION_MS = 220.0

QRS_WIDE_EVIDENCE_MS = 120.0
QRS_WIDTH_DIFFERENCE_EVIDENCE_MS = 20.0

REFERENCE_MIN_BEATS = 3
REFERENCE_MAX_BEATS = 20
REFERENCE_TRIGGER_EXCLUSION_BEATS = 1
BEAT_MAX_INVALID_PERCENT = 5.0

MORPHOLOGY_ALIGNMENT_MS = 40.0
MORPHOLOGY_ABNORMAL_SCORE = 0.55

PREMATURE_COUPLING_RATIO = 0.85
FULL_COMPENSATORY_PAUSE_RATIO_LOW = 1.80
FULL_COMPENSATORY_PAUSE_RATIO_HIGH = 2.20
INCOMPLETE_COMPENSATORY_PAUSE_RATIO_LOW = 1.45

QUALITY_GRADE_BOUNDS = (
    (90.0, "excellent"),
    (75.0, "good"),
    (55.0, "fair"),
    (0.0, "poor"),
)

CONFIDENCE_GRADE_BOUNDS = (
    (80.0, "high"),
    (55.0, "moderate"),
    (30.0, "low"),
    (0.0, "insufficient"),
)

MORPHOLOGY_GRADE_BOUNDS = (
    (0.25, "similar"),
    (0.45, "mildly_different"),
    (0.65, "moderately_different"),
    (1.01, "markedly_different"),
)